Add regression test logic to pipeline

diff --git a/.github/workflows/continuous-deploy.yml b/.github/workflows/continuous-deploy.yml
--- a/.github/workflows/continuous-deploy.yml
+++ b/.github/workflows/continuous-deploy.yml
@@ -460,73 +460,73 @@ jobs:
             $REDIS_HOST:$REDIS_PORT \
             FLUSHALL
 
-      - name: Helmfile Apply # Apply default helmfile (without RDS proxy) when resetting deployments.
-        if: github.event.inputs.run-reset-deployments == 'true'
-        uses: helmfile/helmfile-action@v1.9.1
-        with:
-          helmfile-args: |
-            apply \
-              --environment ${{ vars.ENVIRONMENT }} \
-              -f ./charts/helmfiles/aries-cloudapi-python.yaml \
-              --state-values-set image.tag=${{ env.IMAGE_TAG }} \
-              --state-values-set image.registry=ghcr.io/${{ github.repository_owner }}
-          helm-plugins: |
-            https://github.com/databus23/helm-diff,
-            https://github.com/jkroepke/helm-secrets
-          helmfile-version: ${{ env.HELMFILE_VERSION }}
-          helm-version: ${{ env.HELM_VERSION }}
-        env:
-          IMAGE_TAG: ${{ needs.build.outputs.image_version }}
+      # - name: Helmfile Apply # Apply default helmfile (without RDS proxy) when resetting deployments.
+      #   if: github.event.inputs.run-reset-deployments == 'true'
+      #   uses: helmfile/helmfile-action@v1.9.1
+      #   with:
+      #     helmfile-args: |
+      #       apply \
+      #         --environment ${{ vars.ENVIRONMENT }} \
+      #         -f ./charts/helmfiles/aries-cloudapi-python.yaml \
+      #         --state-values-set image.tag=${{ env.IMAGE_TAG }} \
+      #         --state-values-set image.registry=ghcr.io/${{ github.repository_owner }}
+      #     helm-plugins: |
+      #       https://github.com/databus23/helm-diff,
+      #       https://github.com/jkroepke/helm-secrets
+      #     helmfile-version: ${{ env.HELMFILE_VERSION }}
+      #     helm-version: ${{ env.HELM_VERSION }}
+      #   env:
+      #     IMAGE_TAG: ${{ needs.build.outputs.image_version }}
 
-      - name: Helmfile Apply (Exclude Agents) # Always exclude agents and apply (zero diff if resetting deployments)
-        uses: helmfile/helmfile-action@v1.9.1
-        with:
-          helmfile-args: |
-            apply \
-              --environment ${{ vars.ENVIRONMENT }} \
-              -f ./charts/helmfiles/aries-cloudapi-python.yaml \
-              --state-values-set image.tag=${{ env.IMAGE_TAG }} \
-              --state-values-set image.registry=ghcr.io/${{ github.repository_owner }} \
-              --selector app!=governance-ga-agent,app!=governance-multitenant-agent
-          helm-plugins: |
-            https://github.com/databus23/helm-diff,
-            https://github.com/jkroepke/helm-secrets
-          helmfile-version: ${{ env.HELMFILE_VERSION }}
-          helm-version: ${{ env.HELM_VERSION }}
-        env:
-          IMAGE_TAG: ${{ needs.build.outputs.image_version }}
+      # - name: Helmfile Apply (Exclude Agents) # Always exclude agents and apply (zero diff if resetting deployments)
+      #   uses: helmfile/helmfile-action@v1.9.1
+      #   with:
+      #     helmfile-args: |
+      #       apply \
+      #         --environment ${{ vars.ENVIRONMENT }} \
+      #         -f ./charts/helmfiles/aries-cloudapi-python.yaml \
+      #         --state-values-set image.tag=${{ env.IMAGE_TAG }} \
+      #         --state-values-set image.registry=ghcr.io/${{ github.repository_owner }} \
+      #         --selector app!=governance-ga-agent,app!=governance-multitenant-agent
+      #     helm-plugins: |
+      #       https://github.com/databus23/helm-diff,
+      #       https://github.com/jkroepke/helm-secrets
+      #     helmfile-version: ${{ env.HELMFILE_VERSION }}
+      #     helm-version: ${{ env.HELM_VERSION }}
+      #   env:
+      #     IMAGE_TAG: ${{ needs.build.outputs.image_version }}
 
-      - name: Create values file
-        run: |
-          echo 'env:' > ./charts/helmfiles/acapy-wallet-storage-config.yaml
-          echo '  ACAPY_WALLET_STORAGE_CONFIG: |-' >> ./charts/helmfiles/acapy-wallet-storage-config.yaml
-          echo '    ${{ secrets.ACAPY_WALLET_STORAGE_CONFIG }}' >> ./charts/helmfiles/acapy-wallet-storage-config.yaml
-          pwd
-          ls -la
+      # - name: Create values file
+      #   run: |
+      #     echo 'env:' > ./charts/helmfiles/acapy-wallet-storage-config.yaml
+      #     echo '  ACAPY_WALLET_STORAGE_CONFIG: |-' >> ./charts/helmfiles/acapy-wallet-storage-config.yaml
+      #     echo '    ${{ secrets.ACAPY_WALLET_STORAGE_CONFIG }}' >> ./charts/helmfiles/acapy-wallet-storage-config.yaml
+      #     pwd
+      #     ls -la
 
-      - name: Helmfile Patch Proxy # Always patch agents with proxy.
-        id: patch_proxy
-        uses: helmfile/helmfile-action@v1.9.1
-        with:
-          helmfile-args: |
-            apply \
-              --environment ${{ vars.ENVIRONMENT }} \
-              -f ./charts/helmfiles/aries-cloudapi-python.yaml \
-              --state-values-set image.tag=${{ env.IMAGE_TAG }} \
-              --state-values-set image.registry=ghcr.io/${{ github.repository_owner }} \
-              --selector app=governance-ga-agent \
-              --selector app=governance-multitenant-agent \
-              --set env.WALLET_DB_HOST=${{ secrets.DB_PROXY_HOST }} \
-              --values acapy-wallet-storage-config.yaml
-          helm-plugins: |
-            https://github.com/databus23/helm-diff,
-            https://github.com/jkroepke/helm-secrets
-          helmfile-version: ${{ env.HELMFILE_VERSION }}
-          helm-version: ${{ env.HELM_VERSION }}
-        env:
-          IMAGE_TAG: ${{ needs.build.outputs.image_version }}
+      # - name: Helmfile Patch Proxy # Always patch agents with proxy.
+      #   id: patch_proxy
+      #   uses: helmfile/helmfile-action@v1.9.1
+      #   with:
+      #     helmfile-args: |
+      #       apply \
+      #         --environment ${{ vars.ENVIRONMENT }} \
+      #         -f ./charts/helmfiles/aries-cloudapi-python.yaml \
+      #         --state-values-set image.tag=${{ env.IMAGE_TAG }} \
+      #         --state-values-set image.registry=ghcr.io/${{ github.repository_owner }} \
+      #         --selector app=governance-ga-agent \
+      #         --selector app=governance-multitenant-agent \
+      #         --set env.WALLET_DB_HOST=${{ secrets.DB_PROXY_HOST }} \
+      #         --values acapy-wallet-storage-config.yaml
+      #     helm-plugins: |
+      #       https://github.com/databus23/helm-diff,
+      #       https://github.com/jkroepke/helm-secrets
+      #     helmfile-version: ${{ env.HELMFILE_VERSION }}
+      #     helm-version: ${{ env.HELM_VERSION }}
+      #   env:
+      #     IMAGE_TAG: ${{ needs.build.outputs.image_version }}
 
-      - name: Helmfile apply pytest
+      - name: Helmfile run pytest
         if: ${{ github.event_name != 'workflow_dispatch' || (github.event_name == 'workflow_dispatch' && github.event.inputs.run-tests != 'false') }}
         id: pytest
         uses: helmfile/helmfile-action@v1.9.1
@@ -537,7 +537,9 @@ jobs:
               -f ./charts/helmfiles/aries-capi-test.yaml \
               --set image.tag=${{ env.IMAGE_TAG }} \
               --set image.registry=ghcr.io/${{ github.repository_owner }} \
-              --set completions=${{ env.PYTEST_COMPLETIONS }}
+              --set completions=${{ env.PYTEST_COMPLETIONS }} \
+              --state-values-set release=cloudapi-pytest \
+              --set fullnameOverride=cloudapi-pytest
           helm-plugins: |
             https://github.com/databus23/helm-diff,
             https://github.com/jkroepke/helm-secrets
@@ -546,8 +548,55 @@ jobs:
         env:
           IMAGE_TAG: ${{ needs.build.outputs.image_version }}
 
+      - name: Helmfile init regression pytest
+        if: github.event.inputs.run-reset-deployments == 'true'
+        id: pytest-init-regression
+        uses: helmfile/helmfile-action@v1.9.1
+        with:
+          helmfile-args: |
+            apply \
+              --environment ${{ vars.ENVIRONMENT }} \
+              -f ./charts/helmfiles/aries-capi-test.yaml \
+              --set image.tag=${{ env.IMAGE_TAG }} \
+              --set image.registry=ghcr.io/${{ github.repository_owner }} \
+              --set completions=${{ env.PYTEST_COMPLETIONS }} \
+              --state-values-set release=cloudapi-pytest-regression \
+              --set fullnameOverride=cloudapi-pytest-regression
+          helm-plugins: |
+            https://github.com/databus23/helm-diff,
+            https://github.com/jkroepke/helm-secrets
+          helmfile-version: ${{ env.HELMFILE_VERSION }}
+          helm-version: ${{ env.HELM_VERSION }}
+        env:
+          IMAGE_TAG: ${{ needs.build.outputs.image_version }}
+          RUN_REGRESSION_TESTS: true
+
+      - name: Helmfile run regression pytest
+        if: ${{ github.event_name != 'workflow_dispatch' || (github.event_name == 'workflow_dispatch' && github.event.inputs.run-tests != 'false' && github.event.inputs.run-reset-deployments == 'false') }}
+        id: pytest-run-regression
+        uses: helmfile/helmfile-action@v1.9.1
+        with:
+          helmfile-args: |
+            apply \
+              --environment ${{ vars.ENVIRONMENT }} \
+              -f ./charts/helmfiles/aries-capi-test.yaml \
+              --set image.tag=${{ env.IMAGE_TAG }} \
+              --set image.registry=ghcr.io/${{ github.repository_owner }} \
+              --set completions=${{ env.PYTEST_COMPLETIONS }} \
+              --state-values-set release=cloudapi-pytest-regression \
+              --set fullnameOverride=cloudapi-pytest-regression
+          helm-plugins: |
+            https://github.com/databus23/helm-diff,
+            https://github.com/jkroepke/helm-secrets
+          helmfile-version: ${{ env.HELMFILE_VERSION }}
+          helm-version: ${{ env.HELM_VERSION }}
+        env:
+          IMAGE_TAG: ${{ needs.build.outputs.image_version }}
+          RUN_REGRESSION_TESTS: true
+          FAIL_ON_RECREATING_FIXTURES: true
+
       - name: Wait for pytest and print logs
-        if: ${{ github.event_name != 'workflow_dispatch' || (github.event_name == 'workflow_dispatch' && github.event.inputs.run-tests != 'false') }}
+        if: steps.pytest.outcome == 'success'
         run: |
           while true; do
             # Check if the job is complete or failed
@@ -577,8 +626,39 @@ jobs:
           JOB_NAME: cloudapi-pytest
           NAMESPACE: dev-cloudapi
 
+      - name: Wait for pytest regression and print logs
+        if: steps.pytest-init-regression.outcome == 'success' || steps.pytest-run-regression.outcome == 'success'
+        run: |
+          while true; do
+            # Check if the job is complete or failed
+            COMPLETION_STATUS=$(kubectl get job $JOB_NAME -n $NAMESPACE -o jsonpath='{.status.succeeded}')
+            FAILURE_STATUS=$(kubectl get job $JOB_NAME -n $NAMESPACE -o jsonpath='{.status.failed}')
+
+            if [ "$COMPLETION_STATUS" == "${{ env.PYTEST_COMPLETIONS }}" ] || [ "$FAILURE_STATUS" == "1" ]; then
+                echo "Job $JOB_NAME has completed."
+                break
+            else
+                echo "Waiting for job to complete..."
+                sleep 10
+            fi
+          done
+
+          # Get all pods for the job
+          pods=$(kubectl get pods -n $NAMESPACE --selector=job-name=$JOB_NAME -o jsonpath='{.items[*].metadata.name}')
+
+          # Loop through the pods and get logs
+          for pod in $pods
+          do
+              echo "Logs for Pod: $pod"
+              kubectl logs -n $NAMESPACE $pod
+          done
+
+        env:
+          JOB_NAME: cloudapi-pytest-regression
+          NAMESPACE: dev-cloudapi
+
       - name: Copy k8s pytest results
-        if: ${{ github.event_name != 'workflow_dispatch' || (github.event_name == 'workflow_dispatch' && github.event.inputs.run-tests != 'false') }}
+        if: steps.pytest.outcome == 'success'
         run: |
           echo "apiVersion: v1
           kind: Pod
@@ -607,6 +687,7 @@ jobs:
 
           # Copy the file from the pod to your local system
           echo "Copying file from pod..."
+          mkdir -p $LOCAL_PATH
           kubectl -n $NAMESPACE cp $POD_NAME:$MOUNT_PATH/$OUTPUT_FILE $LOCAL_PATH/$OUTPUT_FILE
           kubectl -n $NAMESPACE cp $POD_NAME:$MOUNT_PATH/$COVERAGE_FILE $LOCAL_PATH/$COVERAGE_FILE
 
@@ -620,30 +701,88 @@ jobs:
           POD_NAME: pytest-results
           CONTAINER_IMAGE: busybox
           MOUNT_PATH: /mnt
-          LOCAL_PATH: ./
+          LOCAL_PATH: ./pytest
           NAMESPACE: dev-cloudapi
 
-      - name: Publish Test Report
+      - name: Copy k8s pytest regression results
+        if: steps.pytest-init-regression.outcome == 'success' || steps.pytest-run-regression.outcome == 'success'
+        run: |
+          echo "apiVersion: v1
+          kind: Pod
+          metadata:
+            name: $POD_NAME
+            namespace: $NAMESPACE
+          spec:
+            containers:
+            - name: $POD_NAME
+              image: $CONTAINER_IMAGE
+              command: [\"sleep\", \"3600\"]
+              volumeMounts:
+              - name: my-volume
+                mountPath: $MOUNT_PATH
+            volumes:
+            - name: my-volume
+              persistentVolumeClaim:
+                claimName: $PVC_NAME
+            restartPolicy: Never" > busybox-pod.yaml
+
+          kubectl apply -f busybox-pod.yaml
+
+          # Wait for the pod to be ready
+          echo "Waiting for pod to be ready..."
+          kubectl -n $NAMESPACE wait --for=condition=ready pod/$POD_NAME --timeout=60s
+
+          # Copy the file from the pod to your local system
+          echo "Copying file from pod..."
+          mkdir -p $LOCAL_PATH
+          kubectl -n $NAMESPACE cp $POD_NAME:$MOUNT_PATH/$OUTPUT_FILE $LOCAL_PATH/$OUTPUT_FILE
+          kubectl -n $NAMESPACE cp $POD_NAME:$MOUNT_PATH/$COVERAGE_FILE $LOCAL_PATH/$COVERAGE_FILE
+
+          # Clean up: delete the temporary pod
+          echo "Cleaning up..."
+          kubectl -n $NAMESPACE delete pod $POD_NAME
+
+          echo "Done!"
+        env:
+          PVC_NAME: cloudapi-pytest-regression
+          POD_NAME: pytest-results-regression
+          CONTAINER_IMAGE: busybox
+          MOUNT_PATH: /mnt
+          LOCAL_PATH: ./pytest-regression
+          NAMESPACE: dev-cloudapi
+
+      - name: Publish Pytest Report
         uses: mikepenz/action-junit-report@v4
-        if: ${{ github.event_name != 'workflow_dispatch' || (github.event_name == 'workflow_dispatch' && github.event.inputs.run-tests != 'false') }}
+        if: steps.pytest.outcome == 'success'
         with:
-          report_paths: "./test_output.xml"
+          check_name: JUnit Test Report
+          report_paths: "./pytest/test_output.xml"
           fail_on_failure: true
           detailed_summary: true
           require_passed_tests: true
 
-      - name: Pytest coverage comment
-        if: (
-          github.event_name == 'pull_request' ||
-          (github.event_name == 'workflow_dispatch' && github.event.inputs.run-tests != 'false')
-          )
-        uses: MishaKav/pytest-coverage-comment@v1.1.51
+      - name: Publish Pytest Regression Report
+        uses: mikepenz/action-junit-report@v4
+        if: steps.pytest-init-regression.outcome == 'success' || steps.pytest-run-regression.outcome == 'success'
         with:
-          pytest-coverage-path: ./test_coverage.txt
-          junitxml-path: ./test_output.xml
-          create-new-comment: true
-          # Resolves `Warning: Your comment is too long (maximum is 65536 characters), coverage report will not be added.`
-          hide-report: ${{ github.event_name != 'pull_request' }}
+          check_name: JUnit Test Report Regression
+          report_paths: "./pytest-regression/test_output.xml"
+          fail_on_failure: true
+          detailed_summary: true
+          require_passed_tests: true
+
+      # - name: Pytest coverage comment
+      #   if: (
+      #     github.event_name == 'pull_request' ||
+      #     (github.event_name == 'workflow_dispatch' && github.event.inputs.run-tests != 'false')
+      #     )
+      #   uses: MishaKav/pytest-coverage-comment@v1.1.51
+      #   with:
+      #     pytest-coverage-path: ./test_coverage.txt
+      #     junitxml-path: ./test_output.xml
+      #     create-new-comment: true
+      #     # Resolves `Warning: Your comment is too long (maximum is 65536 characters), coverage report will not be added.`
+      #     hide-report: ${{ github.event_name != 'pull_request' }}
 
       - name: Helmfile destroy pytest
         uses: helmfile/helmfile-action@v1.9.1
@@ -652,7 +791,26 @@ jobs:
           helmfile-args: |
             destroy \
               --environment ${{ vars.ENVIRONMENT }} \
-              -f ./charts/helmfiles/aries-capi-test.yaml
+              -f ./charts/helmfiles/aries-capi-test.yaml \
+              --state-values-set release=cloudapi-pytest \
+              --set fullnameOverride=cloudapi-pytest
+          helm-plugins: |
+            https://github.com/databus23/helm-diff
+          helmfile-version: ${{ env.HELMFILE_VERSION }}
+          helm-version: ${{ env.HELM_VERSION }}
+        env:
+          IMAGE_TAG: ${{ needs.build.outputs.image_version }}
+
+      - name: Helmfile destroy pytest regression
+        uses: helmfile/helmfile-action@v1.9.1
+        if: always()
+        with:
+          helmfile-args: |
+            destroy \
+              --environment ${{ vars.ENVIRONMENT }} \
+              -f ./charts/helmfiles/aries-capi-test.yaml \
+              --state-values-set release=cloudapi-pytest-regression \
+              --set fullnameOverride=cloudapi-pytest-regression
           helm-plugins: |
             https://github.com/databus23/helm-diff
           helmfile-version: ${{ env.HELMFILE_VERSION }}
