Add regression test logic to pipeline (#806)
* Add regression test logic to pipeline

* Get branch for workflow dispatch

* increase timeout to 35 minutes

* :construction_worker: Update example of forked version

* :art: modify sample_indy_proof_request to take custom restrictions

* :sparkles: add restrictions to proof requests that expect cred of specific cred_def_id

* Fix coverage comment coverage path

---------

Co-authored-by: ff137 <ff137@proton.me>

diff --git a/.github/workflows/continuous-deploy.yml b/.github/workflows/continuous-deploy.yml
--- a/.github/workflows/continuous-deploy.yml
+++ b/.github/workflows/continuous-deploy.yml
@@ -13,6 +13,11 @@ on:
         required: false
         default: true
         type: boolean
+      run-regression-tests:
+        description: "Run regression tests step"
+        required: false
+        default: true
+        type: boolean
 
   push:
     branches:
@@ -314,7 +319,7 @@ jobs:
       pull-requests: write # Required to comment on PRs for Pytest coverage comment
     runs-on: ubuntu-latest
 
-    timeout-minutes: 30
+    timeout-minutes: 35
 
     env:
       TAILSCALE_VERSION: 1.62.1
@@ -338,18 +343,26 @@ jobs:
       - name: Authenticate GitHub CLI
         run: echo "${{ secrets.PAT }}" | gh auth login --with-token
 
+      - name: Set branch name
+        id: set_branch_name
+        run: |
+          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
+            echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
+          else
+            echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | cut -d/ -f2-)" >> $GITHUB_ENV
+          fi
+
       - name: Check if branch exists
         id: check_branch
-        env:
-          BRANCH_NAME: ${{ github.head_ref }}
-          DEFAULT_BRANCH: master
         run: |
+          DEFAULT_BRANCH=master
+
           if gh api repos/didx-xyz/charts/git/ref/heads/$BRANCH_NAME; then
-            echo "branch_exists=true" >> $GITHUB_OUTPUT
-            echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
+            echo "branch_exists=true" >> $GITHUB_ENV
+            echo "branch_name=$BRANCH_NAME" >> $GITHUB_ENV
           else
-            echo "branch_exists=false" >> $GITHUB_OUTPUT
-            echo "branch_name=$DEFAULT_BRANCH" >> $GITHUB_OUTPUT
+            echo "branch_exists=false" >> $GITHUB_ENV
+            echo "branch_name=$DEFAULT_BRANCH" >> $GITHUB_ENV
           fi
 
       - name: Checkout Charts
@@ -358,7 +371,7 @@ jobs:
           repository: didx-xyz/charts
           token: ${{ secrets.PAT }}
           path: charts
-          ref: ${{ steps.check_branch.outputs.branch_name }}
+          ref: ${{ env.branch_name }}
 
       - name: Install dependencies
         run: sudo apt-get install -y postgresql-client redis-tools
@@ -381,23 +394,23 @@ jobs:
           authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
           version: ${{ env.TAILSCALE_VERSION }}
 
-      - name: Helmfile Diff
-        if: github.event.inputs.run-reset-deployments == 'true'
-        uses: helmfile/helmfile-action@v1.9.1
-        with:
-          helmfile-args: |
-            diff \
-              --environment ${{ vars.ENVIRONMENT }} \
-              -f ./charts/helmfiles/aries-cloudapi-python.yaml \
-              --set image.tag=${{ env.IMAGE_TAG }} \
-              --set image.registry=ghcr.io/${{ github.repository_owner }}
-          helm-plugins: |
-            https://github.com/databus23/helm-diff,
-            https://github.com/jkroepke/helm-secrets
-          helmfile-version: ${{ env.HELMFILE_VERSION }}
-          helm-version: ${{ env.HELM_VERSION }}
-        env:
-          IMAGE_TAG: ${{ needs.build.outputs.image_version }}
+      # - name: Helmfile Diff
+      #   if: github.event.inputs.run-reset-deployments == 'true'
+      #   uses: helmfile/helmfile-action@v1.9.1
+      #   with:
+      #     helmfile-args: |
+      #       diff \
+      #         --environment ${{ vars.ENVIRONMENT }} \
+      #         -f ./charts/helmfiles/aries-cloudapi-python.yaml \
+      #         --set image.tag=${{ env.IMAGE_TAG }} \
+      #         --set image.registry=ghcr.io/${{ github.repository_owner }}
+      #     helm-plugins: |
+      #       https://github.com/databus23/helm-diff,
+      #       https://github.com/jkroepke/helm-secrets
+      #     helmfile-version: ${{ env.HELMFILE_VERSION }}
+      #     helm-version: ${{ env.HELM_VERSION }}
+      #   env:
+      #     IMAGE_TAG: ${{ needs.build.outputs.image_version }}
 
       - name: Helmfile Destroy
         id: destroy_deployments
@@ -479,6 +492,7 @@ jobs:
           IMAGE_TAG: ${{ needs.build.outputs.image_version }}
 
       - name: Helmfile Apply (Exclude Agents) # Always exclude agents and apply (zero diff if resetting deployments)
+        if: github.event.inputs.run-reset-deployments != 'true'
         uses: helmfile/helmfile-action@v1.9.1
         with:
           helmfile-args: |
@@ -526,7 +540,7 @@ jobs:
         env:
           IMAGE_TAG: ${{ needs.build.outputs.image_version }}
 
-      - name: Helmfile apply pytest
+      - name: Helmfile run pytest
         if: ${{ github.event_name != 'workflow_dispatch' || (github.event_name == 'workflow_dispatch' && github.event.inputs.run-tests != 'false') }}
         id: pytest
         uses: helmfile/helmfile-action@v1.9.1
@@ -537,7 +551,56 @@ jobs:
               -f ./charts/helmfiles/aries-capi-test.yaml \
               --set image.tag=${{ env.IMAGE_TAG }} \
               --set image.registry=ghcr.io/${{ github.repository_owner }} \
-              --set completions=${{ env.PYTEST_COMPLETIONS }}
+              --set completions=${{ env.PYTEST_COMPLETIONS }} \
+              --state-values-set release=cloudapi-pytest \
+              --set fullnameOverride=cloudapi-pytest
+          helm-plugins: |
+            https://github.com/databus23/helm-diff,
+            https://github.com/jkroepke/helm-secrets
+          helmfile-version: ${{ env.HELMFILE_VERSION }}
+          helm-version: ${{ env.HELM_VERSION }}
+        env:
+          IMAGE_TAG: ${{ needs.build.outputs.image_version }}
+
+      - name: Helmfile init regression pytest
+        if: github.event.inputs.run-reset-deployments == 'true' && github.event.inputs.run-regression-tests == 'true'
+        id: pytest-init-regression
+        uses: helmfile/helmfile-action@v1.9.1
+        with:
+          helmfile-args: |
+            apply \
+              --environment ${{ vars.ENVIRONMENT }} \
+              -f ./charts/helmfiles/aries-capi-test.yaml \
+              --set image.tag=${{ env.IMAGE_TAG }} \
+              --set image.registry=ghcr.io/${{ github.repository_owner }} \
+              --set completions=${{ env.PYTEST_COMPLETIONS }} \
+              --state-values-set release=cloudapi-pytest-regression \
+              --set fullnameOverride=cloudapi-pytest-regression \
+              --set env.RUN_REGRESSION_TESTS="true"
+          helm-plugins: |
+            https://github.com/databus23/helm-diff,
+            https://github.com/jkroepke/helm-secrets
+          helmfile-version: ${{ env.HELMFILE_VERSION }}
+          helm-version: ${{ env.HELM_VERSION }}
+        env:
+          IMAGE_TAG: ${{ needs.build.outputs.image_version }}
+
+      - name: Helmfile run regression pytest
+        if: ${{ github.event_name != 'workflow_dispatch' || (github.event_name == 'workflow_dispatch' && github.event.inputs.run-reset-deployments == 'false' && github.event.inputs.run-regression-tests == 'true') }}
+        id: pytest-run-regression
+        uses: helmfile/helmfile-action@v1.9.1
+        with:
+          helmfile-args: |
+            apply \
+              --environment ${{ vars.ENVIRONMENT }} \
+              -f ./charts/helmfiles/aries-capi-test.yaml \
+              --set image.tag=${{ env.IMAGE_TAG }} \
+              --set image.registry=ghcr.io/${{ github.repository_owner }} \
+              --set completions=${{ env.PYTEST_COMPLETIONS }} \
+              --state-values-set release=cloudapi-pytest-regression \
+              --set fullnameOverride=cloudapi-pytest-regression \
+              --set env.RUN_REGRESSION_TESTS="true" \
+              --set env.FAIL_ON_RECREATING_FIXTURES="true"
           helm-plugins: |
             https://github.com/databus23/helm-diff,
             https://github.com/jkroepke/helm-secrets
@@ -547,7 +610,7 @@ jobs:
           IMAGE_TAG: ${{ needs.build.outputs.image_version }}
 
       - name: Wait for pytest and print logs
-        if: ${{ github.event_name != 'workflow_dispatch' || (github.event_name == 'workflow_dispatch' && github.event.inputs.run-tests != 'false') }}
+        if: steps.pytest.outcome == 'success'
         run: |
           while true; do
             # Check if the job is complete or failed
@@ -577,8 +640,39 @@ jobs:
           JOB_NAME: cloudapi-pytest
           NAMESPACE: dev-cloudapi
 
+      - name: Wait for pytest regression and print logs
+        if: steps.pytest-init-regression.outcome == 'success' || steps.pytest-run-regression.outcome == 'success'
+        run: |
+          while true; do
+            # Check if the job is complete or failed
+            COMPLETION_STATUS=$(kubectl get job $JOB_NAME -n $NAMESPACE -o jsonpath='{.status.succeeded}')
+            FAILURE_STATUS=$(kubectl get job $JOB_NAME -n $NAMESPACE -o jsonpath='{.status.failed}')
+
+            if [ "$COMPLETION_STATUS" == "${{ env.PYTEST_COMPLETIONS }}" ] || [ "$FAILURE_STATUS" == "1" ]; then
+                echo "Job $JOB_NAME has completed."
+                break
+            else
+                echo "Waiting for job to complete..."
+                sleep 10
+            fi
+          done
+
+          # Get all pods for the job
+          pods=$(kubectl get pods -n $NAMESPACE --selector=job-name=$JOB_NAME -o jsonpath='{.items[*].metadata.name}')
+
+          # Loop through the pods and get logs
+          for pod in $pods
+          do
+              echo "Logs for Pod: $pod"
+              kubectl logs -n $NAMESPACE $pod
+          done
+
+        env:
+          JOB_NAME: cloudapi-pytest-regression
+          NAMESPACE: dev-cloudapi
+
       - name: Copy k8s pytest results
-        if: ${{ github.event_name != 'workflow_dispatch' || (github.event_name == 'workflow_dispatch' && github.event.inputs.run-tests != 'false') }}
+        if: steps.pytest.outcome == 'success'
         run: |
           echo "apiVersion: v1
           kind: Pod
@@ -607,6 +701,7 @@ jobs:
 
           # Copy the file from the pod to your local system
           echo "Copying file from pod..."
+          mkdir -p $LOCAL_PATH
           kubectl -n $NAMESPACE cp $POD_NAME:$MOUNT_PATH/$OUTPUT_FILE $LOCAL_PATH/$OUTPUT_FILE
           kubectl -n $NAMESPACE cp $POD_NAME:$MOUNT_PATH/$COVERAGE_FILE $LOCAL_PATH/$COVERAGE_FILE
 
@@ -620,30 +715,97 @@ jobs:
           POD_NAME: pytest-results
           CONTAINER_IMAGE: busybox
           MOUNT_PATH: /mnt
-          LOCAL_PATH: ./
+          LOCAL_PATH: ./pytest
           NAMESPACE: dev-cloudapi
 
-      - name: Publish Test Report
+      - name: Copy k8s pytest regression results
+        if: steps.pytest-init-regression.outcome == 'success' || steps.pytest-run-regression.outcome == 'success'
+        run: |
+          echo "apiVersion: v1
+          kind: Pod
+          metadata:
+            name: $POD_NAME
+            namespace: $NAMESPACE
+          spec:
+            containers:
+            - name: $POD_NAME
+              image: $CONTAINER_IMAGE
+              command: [\"sleep\", \"3600\"]
+              volumeMounts:
+              - name: my-volume
+                mountPath: $MOUNT_PATH
+            volumes:
+            - name: my-volume
+              persistentVolumeClaim:
+                claimName: $PVC_NAME
+            restartPolicy: Never" > busybox-pod.yaml
+
+          kubectl apply -f busybox-pod.yaml
+
+          # Wait for the pod to be ready
+          echo "Waiting for pod to be ready..."
+          kubectl -n $NAMESPACE wait --for=condition=ready pod/$POD_NAME --timeout=60s
+
+          # Copy the file from the pod to your local system
+          echo "Copying file from pod..."
+          mkdir -p $LOCAL_PATH
+          kubectl -n $NAMESPACE cp $POD_NAME:$MOUNT_PATH/$OUTPUT_FILE $LOCAL_PATH/$OUTPUT_FILE
+          kubectl -n $NAMESPACE cp $POD_NAME:$MOUNT_PATH/$COVERAGE_FILE $LOCAL_PATH/$COVERAGE_FILE
+
+          # Clean up: delete the temporary pod
+          echo "Cleaning up..."
+          kubectl -n $NAMESPACE delete pod $POD_NAME
+
+          echo "Done!"
+        env:
+          PVC_NAME: cloudapi-pytest-regression
+          POD_NAME: pytest-results-regression
+          CONTAINER_IMAGE: busybox
+          MOUNT_PATH: /mnt
+          LOCAL_PATH: ./pytest-regression
+          NAMESPACE: dev-cloudapi
+
+      - name: Publish Pytest Report
         uses: mikepenz/action-junit-report@v4
-        if: ${{ github.event_name != 'workflow_dispatch' || (github.event_name == 'workflow_dispatch' && github.event.inputs.run-tests != 'false') }}
+        if: steps.pytest.outcome == 'success'
         with:
-          report_paths: "./test_output.xml"
+          check_name: JUnit Test Report
+          report_paths: "./pytest/test_output.xml"
+          fail_on_failure: true
+          detailed_summary: true
+          require_passed_tests: true
+
+      - name: Publish Pytest Regression Report
+        uses: mikepenz/action-junit-report@v4
+        if: steps.pytest-init-regression.outcome == 'success' || steps.pytest-run-regression.outcome == 'success'
+        with:
+          check_name: JUnit Test Report Regression
+          report_paths: "./pytest-regression/test_output.xml"
           fail_on_failure: true
           detailed_summary: true
           require_passed_tests: true
 
       - name: Pytest coverage comment
-        if: (
-          github.event_name == 'pull_request' ||
-          (github.event_name == 'workflow_dispatch' && github.event.inputs.run-tests != 'false')
-          )
+        if: steps.pytest.outcome == 'success'
         uses: MishaKav/pytest-coverage-comment@v1.1.51
         with:
-          pytest-coverage-path: ./test_coverage.txt
-          junitxml-path: ./test_output.xml
+          pytest-coverage-path: ./pytest/test_coverage.txt
+          junitxml-path: ./pytest/test_output.xml
           create-new-comment: true
+          title: "K8s Test Coverage"
           # Resolves `Warning: Your comment is too long (maximum is 65536 characters), coverage report will not be added.`
-          hide-report: ${{ github.event_name != 'pull_request' }}
+          # hide-report: ${{ github.event_name != 'pull_request' }}
+
+      - name: Pytest coverage comment
+        if: steps.pytest-init-regression.outcome == 'success' || steps.pytest-run-regression.outcome == 'success'
+        uses: MishaKav/pytest-coverage-comment@v1.1.51
+        with:
+          pytest-coverage-path: ./pytest-regression/test_coverage.txt
+          junitxml-path: ./pytest-regression/test_output.xml
+          create-new-comment: true
+          title: "K8s Regression Test Coverage"
+          # Resolves `Warning: Your comment is too long (maximum is 65536 characters), coverage report will not be added.`
+          # hide-report: ${{ github.event_name != 'pull_request' }}
 
       - name: Helmfile destroy pytest
         uses: helmfile/helmfile-action@v1.9.1
@@ -652,7 +814,24 @@ jobs:
           helmfile-args: |
             destroy \
               --environment ${{ vars.ENVIRONMENT }} \
-              -f ./charts/helmfiles/aries-capi-test.yaml
+              -f ./charts/helmfiles/aries-capi-test.yaml \
+              --state-values-set release=cloudapi-pytest
+          helm-plugins: |
+            https://github.com/databus23/helm-diff
+          helmfile-version: ${{ env.HELMFILE_VERSION }}
+          helm-version: ${{ env.HELM_VERSION }}
+        env:
+          IMAGE_TAG: ${{ needs.build.outputs.image_version }}
+
+      - name: Helmfile destroy pytest regression
+        uses: helmfile/helmfile-action@v1.9.1
+        if: always()
+        with:
+          helmfile-args: |
+            destroy \
+              --environment ${{ vars.ENVIRONMENT }} \
+              -f ./charts/helmfiles/aries-capi-test.yaml \
+              --state-values-set release=cloudapi-pytest-regression
           helm-plugins: |
             https://github.com/databus23/helm-diff
           helmfile-version: ${{ env.HELMFILE_VERSION }}
