specify namespace when copying pytest results

diff --git a/.github/workflows/continuous-deploy.yml b/.github/workflows/continuous-deploy.yml
--- a/.github/workflows/continuous-deploy.yml
+++ b/.github/workflows/continuous-deploy.yml
@@ -345,7 +345,7 @@ jobs:
           version: ${{ env.TAILSCALE_VERSION }}
 
       - name: Helmfile Diff
-        # if: github.event.review.state == 'approved' || github.event_name == 'push' || github.event.inputs.run-update-deployments
+        if: github.event.review.state == 'approved' || github.event_name == 'push' || github.event.inputs.run-update-deployments
         uses: helmfile/helmfile-action@v1.5.0
         with:
           helmfile-args: |
@@ -364,7 +364,7 @@ jobs:
 
       - name: Helmfile Destroy
         id: destroy_deployments
-        # if: github.event.review.state == 'approved' || github.event_name == 'push' || github.event.inputs.run-update-deployments
+        if: github.event.review.state == 'approved' || github.event_name == 'push' || github.event.inputs.run-update-deployments
         uses: helmfile/helmfile-action@v1.5.0
         with:
           helmfile-args: |
@@ -380,7 +380,7 @@ jobs:
           IMAGE_TAG: ${{ needs.build.outputs.image_version }}
 
       - name: Wait for pods to terminate
-        # if: github.event.review.state == 'approved' || github.event_name == 'push' || github.event.inputs.run-update-deployments
+        if: github.event.review.state == 'approved' || github.event_name == 'push' || github.event.inputs.run-update-deployments
         run: |
           while true; do
             terminating_pods_count=$(kubectl -n dev-cloudapi get pods --field-selector=status.phase!=Running,status.phase!=Succeeded -o jsonpath='{.items[*].metadata.name}')
@@ -395,7 +395,7 @@ jobs:
 
       - name: Drop DBs
         id: drop_dbs
-        # if: github.event.review.state == 'approved' || github.event_name == 'push' || github.event.inputs.run-update-deployments
+        if: github.event.review.state == 'approved' || github.event_name == 'push' || github.event.inputs.run-update-deployments
         env:
           DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
           DB_HOST: ${{ secrets.DB_HOST }}
@@ -419,7 +419,7 @@ jobs:
         run: redis-cli -h $REDIS_HOST -p $REDIS_PORT --scan --pattern '*'
 
       - name: Clean Elasticache Redis
-        # if: github.event.review.state == 'approved' || github.event_name == 'push' || github.event.inputs.run-update-deployments
+        if: github.event.review.state == 'approved' || github.event_name == 'push' || github.event.inputs.run-update-deployments
         env:
           REDIS_HOST: ${{ secrets.REDIS_HOST }}
           REDIS_PORT: ${{ secrets.REDIS_PORT }}
@@ -427,7 +427,7 @@ jobs:
 
       - name: Helmfile Apply
         id: update_deployments
-        # if: github.event.review.state == 'approved' || github.event_name == 'push' || github.event.inputs.run-update-deployments
+        if: github.event.review.state == 'approved' || github.event_name == 'push' || github.event.inputs.run-update-deployments
         uses: helmfile/helmfile-action@v1.5.0
         with:
           helmfile-args: |
@@ -482,28 +482,26 @@ jobs:
 
       - name: Copy k8s pytest results
         run: |
-          # Create a temporary pod with the PVC mounted
-          kubectl -n $NAMESPACE run $POD_NAME --image=$CONTAINER_IMAGE --restart=Never --command -- sleep 3600 \
-            --overrides='
-          {
-            "apiVersion": "v1",
-            "spec": {
-              "volumes": [{
-                "name": "my-volume",
-                "persistentVolumeClaim": {
-                  "claimName": "'$PVC_NAME'"
-                }
-              }],
-              "containers": [{
-                "name": "'$POD_NAME'",
-                "image": "'$CONTAINER_IMAGE'",
-                "volumeMounts": [{
-                  "mountPath": "'$MOUNT_PATH'",
-                  "name": "my-volume"
-                }]
-              }]
-            }
-          }'
+          echo "apiVersion: v1
+          kind: Pod
+          metadata:
+            name: $POD_NAME
+            namespace: $NAMESPACE
+          spec:
+            containers:
+            - name: $POD_NAME
+              image: $CONTAINER_IMAGE
+              command: [\"sleep\", \"3600\"]
+              volumeMounts:
+              - name: my-volume
+                mountPath: $MOUNT_PATH
+            volumes:
+            - name: my-volume
+              persistentVolumeClaim:
+                claimName: $PVC_NAME
+            restartPolicy: Never" > busybox-pod.yaml
+
+          kubectl apply -f busybox-pod.yaml
 
           # Wait for the pod to be ready
           echo "Waiting for pod to be ready..."
@@ -511,7 +509,7 @@ jobs:
 
           # Copy the file from the pod to your local system
           echo "Copying file from pod..."
-          kubectl -n $NAMESPACE cp $POD_NAME:$MOUNT_PATH/$OUTPUT_FILE $LOCAL_PATH
+          kubectl -n $NAMESPACE cp $POD_NAME:$MOUNT_PATH/$OUTPUT_FILE $LOCAL_PATH/$OUTPUT_FILE
 
           # Clean up: delete the temporary pod
           echo "Cleaning up..."
@@ -527,6 +525,7 @@ jobs:
           OUTPUT_FILE: test_output.xml
           NAMESPACE: dev-cloudapi
 
+
       - name: Publish Test Report
         uses: mikepenz/action-junit-report@v4
         if: success() || failure() # always run even if the previous step fails
@@ -536,6 +535,7 @@ jobs:
 
       - name: Helmfile destroy pytest
         uses: helmfile/helmfile-action@v1.5.0
+        if: success() || failure() # always run even if the previous step fails
         with:
           helmfile-args: |
             destroy \
