external pytest results (#566)
* external pytest results

* external pytest results

* persistence for pytest results

* specify namespace when copying pytest resuts

* specify namespace when copying pytest results

* Continue if pytest fails

* Force error to test

* Detailed summary

* Coverage

* Run even if previous step fails

* PR write permissions

* workflow dispatch: reset & test logic

* Print pytest logs

* k8s test on every PR commit

* Require passed tests

* Remove whitespace

* Master charts & create new coverage comment

* Master charts & create new coverage comment

diff --git a/.github/workflows/continuous-deploy.yml b/.github/workflows/continuous-deploy.yml
--- a/.github/workflows/continuous-deploy.yml
+++ b/.github/workflows/continuous-deploy.yml
@@ -3,15 +3,15 @@ name: CICD
 on:
   workflow_dispatch:
     inputs:
-      run-update-deployments:
-        description: "Run Update Deployments step manually"
+      run-reset-deployments:
+        description: "Reset deployment: Clean start"
         required: false
-        default: true
+        default: false
         type: boolean
       run-tests:
         description: "Run tests step"
         required: false
-        default: true
+        default: false
         type: boolean
 
   push:
@@ -294,6 +294,8 @@ jobs:
     permissions:
       id-token: write # Required to authenticate with AWS
       contents: read # Required to clone this repository
+      checks: write # Required for action-junit-report
+      pull-requests: write # Required to comment on PRs for Pytest coverage comment
     runs-on: ubuntu-latest
 
     if: github.actor != 'dependabot[bot]'
@@ -302,6 +304,8 @@ jobs:
       TAILSCALE_VERSION: 1.50.1
       HELMFILE_VERSION: v0.157.0
       HELM_VERSION: v3.13.1
+      OUTPUT_FILE: test_output.xml
+      COVERAGE_FILE: test_coverage.txt
 
     concurrency:
       group: cicd-deploy
@@ -343,7 +347,7 @@ jobs:
           version: ${{ env.TAILSCALE_VERSION }}
 
       - name: Helmfile Diff
-        if: github.event.review.state == 'approved' || github.event_name == 'push' || github.event.inputs.run-update-deployments
+        # if: github.event.review.state == 'approved' || github.event_name == 'push' || github.event.inputs.run-reset-deployments == 'true'
         uses: helmfile/helmfile-action@v1.5.0
         with:
           helmfile-args: |
@@ -362,7 +366,7 @@ jobs:
 
       - name: Helmfile Destroy
         id: destroy_deployments
-        if: github.event.review.state == 'approved' || github.event_name == 'push' || github.event.inputs.run-update-deployments
+        if: github.event.inputs.run-reset-deployments == 'true'
         uses: helmfile/helmfile-action@v1.5.0
         with:
           helmfile-args: |
@@ -378,7 +382,7 @@ jobs:
           IMAGE_TAG: ${{ needs.build.outputs.image_version }}
 
       - name: Wait for pods to terminate
-        if: github.event.review.state == 'approved' || github.event_name == 'push' || github.event.inputs.run-update-deployments
+        if: github.event.inputs.run-reset-deployments == 'true'
         run: |
           while true; do
             terminating_pods_count=$(kubectl -n dev-cloudapi get pods --field-selector=status.phase!=Running,status.phase!=Succeeded -o jsonpath='{.items[*].metadata.name}')
@@ -393,7 +397,7 @@ jobs:
 
       - name: Drop DBs
         id: drop_dbs
-        if: github.event.review.state == 'approved' || github.event_name == 'push' || github.event.inputs.run-update-deployments
+        if: github.event.inputs.run-reset-deployments == 'true'
         env:
           DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
           DB_HOST: ${{ secrets.DB_HOST }}
@@ -410,14 +414,14 @@ jobs:
           bash ./scripts/aurora-delete.sh -o $TRUST_REGISTRY_DB_OWNER -c
 
       - name: List Elasticache Redis
-        if: github.event.review.state == 'approved' || github.event_name == 'push' || github.event.inputs.run-update-deployments
+        # if: github.event.review.state == 'approved' || github.event_name == 'push' || github.event.inputs.run-reset-deployments == 'true'
         env:
           REDIS_HOST: ${{ secrets.REDIS_HOST }}
           REDIS_PORT: ${{ secrets.REDIS_PORT }}
         run: redis-cli -h $REDIS_HOST -p $REDIS_PORT --scan --pattern '*'
 
       - name: Clean Elasticache Redis
-        if: github.event.review.state == 'approved' || github.event_name == 'push' || github.event.inputs.run-update-deployments
+        if: github.event.inputs.run-reset-deployments == 'true'
         env:
           REDIS_HOST: ${{ secrets.REDIS_HOST }}
           REDIS_PORT: ${{ secrets.REDIS_PORT }}
@@ -425,7 +429,7 @@ jobs:
 
       - name: Helmfile Apply
         id: update_deployments
-        if: github.event.review.state == 'approved' || github.event_name == 'push' || github.event.inputs.run-update-deployments
+        # if: github.event.review.state == 'approved' || github.event_name == 'push' || github.event.inputs.run-reset-deployments == 'true' || github.event.inputs.run-tests == 'true'
         uses: helmfile/helmfile-action@v1.5.0
         with:
           helmfile-args: |
@@ -437,6 +441,135 @@ jobs:
           helm-plugins: |
             https://github.com/databus23/helm-diff,
             https://github.com/jkroepke/helm-secrets
+          helmfile-version: ${{ env.HELMFILE_VERSION }}
+          helm-version: ${{ env.HELM_VERSION }}
+        env:
+          IMAGE_TAG: ${{ needs.build.outputs.image_version }}
+
+      - name: Helmfile apply pytest
+        # if: github.event.review.state == 'approved' || github.event_name == 'push' || ( github.event.inputs.run-reset-deployments == 'true' && github.event.inputs.run-tests == 'true' ) || github.event.inputs.run-tests == 'true'
+        id: pytest
+        uses: helmfile/helmfile-action@v1.5.0
+        with:
+          helmfile-args: |
+            apply \
+              --environment ${{ vars.ENVIRONMENT }} \
+              -f ./charts/helmfiles/aries-capi-test.yaml \
+              --set image.tag=${{ env.IMAGE_TAG }} \
+              --set image.registry=ghcr.io/${{ github.repository_owner }}
+          helm-plugins: |
+            https://github.com/databus23/helm-diff,
+            https://github.com/jkroepke/helm-secrets
+          helmfile-version: ${{ env.HELMFILE_VERSION }}
+          helm-version: ${{ env.HELM_VERSION }}
+        env:
+          IMAGE_TAG: ${{ needs.build.outputs.image_version }}
+
+      - name: Wait for pytest and print logs
+        # if: github.event.review.state == 'approved' || github.event_name == 'push' || ( github.event.inputs.run-reset-deployments == 'true' && github.event.inputs.run-tests == 'true' ) || github.event.inputs.run-tests == 'true'
+        run: |
+          while true; do
+            # Check if the job is complete or failed
+            COMPLETION_STATUS=$(kubectl get job $JOB_NAME -n $NAMESPACE -o jsonpath='{.status.succeeded}')
+            FAILURE_STATUS=$(kubectl get job $JOB_NAME -n $NAMESPACE -o jsonpath='{.status.failed}')
+
+            if [ "$COMPLETION_STATUS" == "1" ] || [ "$FAILURE_STATUS" == "1" ]; then
+                echo "Job $JOB_NAME has completed."
+                break
+            else
+                echo "Waiting for job to complete..."
+                sleep 10
+            fi
+          done
+
+          # Get all pods for the job
+          pods=$(kubectl get pods -n $NAMESPACE --selector=job-name=$JOB_NAME -o jsonpath='{.items[*].metadata.name}')
+
+          # Loop through the pods and get logs
+          for pod in $pods
+          do
+              echo "Logs for Pod: $pod"
+              kubectl logs -n $NAMESPACE $pod
+          done
+
+        env:
+          JOB_NAME: cloudapi-pytest
+          NAMESPACE: dev-cloudapi
+
+      - name: Copy k8s pytest results
+        # if: github.event.review.state == 'approved' || github.event_name == 'push' || ( github.event.inputs.run-reset-deployments == 'true' && github.event.inputs.run-tests == 'true' ) || github.event.inputs.run-tests == 'true'
+        run: |
+          echo "apiVersion: v1
+          kind: Pod
+          metadata:
+            name: $POD_NAME
+            namespace: $NAMESPACE
+          spec:
+            containers:
+            - name: $POD_NAME
+              image: $CONTAINER_IMAGE
+              command: [\"sleep\", \"3600\"]
+              volumeMounts:
+              - name: my-volume
+                mountPath: $MOUNT_PATH
+            volumes:
+            - name: my-volume
+              persistentVolumeClaim:
+                claimName: $PVC_NAME
+            restartPolicy: Never" > busybox-pod.yaml
+
+          kubectl apply -f busybox-pod.yaml
+
+          # Wait for the pod to be ready
+          echo "Waiting for pod to be ready..."
+          kubectl -n $NAMESPACE wait --for=condition=ready pod/$POD_NAME --timeout=60s
+
+          # Copy the file from the pod to your local system
+          echo "Copying file from pod..."
+          kubectl -n $NAMESPACE cp $POD_NAME:$MOUNT_PATH/$OUTPUT_FILE $LOCAL_PATH/$OUTPUT_FILE
+          kubectl -n $NAMESPACE cp $POD_NAME:$MOUNT_PATH/$COVERAGE_FILE $LOCAL_PATH/$COVERAGE_FILE
+
+          # Clean up: delete the temporary pod
+          echo "Cleaning up..."
+          kubectl -n $NAMESPACE delete pod $POD_NAME
+
+          echo "Done!"
+        env:
+          PVC_NAME: cloudapi-pytest
+          POD_NAME: pytest-results
+          CONTAINER_IMAGE: busybox
+          MOUNT_PATH: /mnt
+          LOCAL_PATH: ./
+          NAMESPACE: dev-cloudapi
+
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: './test_output.xml'
+          fail_on_failure: true
+          detailed_summary: true
+          require_passed_tests: true
+
+      - name: Pytest coverage comment
+        if: success() || failure() # always run even if the previous step fails
+        uses: MishaKav/pytest-coverage-comment@main
+        with:
+          pytest-coverage-path: ./test_coverage.txt
+          junitxml-path: ./test_output.xml
+          create-new-comment: true
+
+      - name: Helmfile destroy pytest
+        uses: helmfile/helmfile-action@v1.5.0
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          helmfile-args: |
+            destroy \
+              --environment ${{ vars.ENVIRONMENT }} \
+              -f ./charts/helmfiles/aries-capi-test.yaml
+          helm-plugins: |
+            https://github.com/databus23/helm-diff
           helmfile-version: ${{ env.HELMFILE_VERSION }}
           helm-version: ${{ env.HELM_VERSION }}
         env:
